### ISSUE TITLE
New users cannot use scoresheet integrations anymore

### ISSUE THREAD

**Issue by skyli42** [alopezlago/MODAQ#186]
MODAQ no longer allows (new) users to login with Google through OAuth2; this breaks the scoresheet integrations for new users. Specifically, when new users attempt to login through Google to give permissions regarding access to Google Drive, they are presented with this screen.
![image](https://user-images.githubusercontent.com/6913825/212764597-a2756a04-50b0-4f01-a648-715f6c8b462d.png)

It seems like this is due to MODAQ reaching Google's 100 user quota for unverified apps ([see here](https://support.google.com/cloud/answer/7454865?hl=en&ref_topic=3473162)).

**Comment by alopezlago** [comment]
I'll take a look when I'm back home. I've tried verifying the app, but they didn't get back to me.

**Comment by alopezlago** [comment]
The old request is still in progress, but they haven't acted upon it for weeks.

**Comment by alopezlago** [comment]
App has been verified; this should now be fixed.
