### ISSUE TITLE
Add ability to upload a roster file to select team/player names from

### ISSUE THREAD

**Issue by ryanrosenberg** [alopezlago/MODAQ#190]
I think the easiest way to standardize team/player names would be to have a roster upload option in the New Game dialog, where staff upload a JSON that, e.g. looks like below, and then can choose from a dropdown for the team/player names. I'm having trouble getting a local copy of MODAQ to run but happy to help if I can.

```
{
    "School A": ["Alice Anderson", "Bob Brown", "Carol Channing", "Dave Davis"],
    "School B": ["Edgar Evers", "Frances Frank", "Guy Guyton", "Hannah Hernandez"]
}
```

**Comment by alopezlago** [comment]
I need to think on this a little bit. I think QBJ has its own way of representing rosters, and when TMS is done it should handle rosters more easily so that MODAQ doesn't need its own experience for it.

**Comment by ryanrosenberg** [comment]
Hm, I was thinking about this more as a small utility to help team/player name entry until TMS is developed.

**Comment by alopezlago** [comment]
That could be interesting... a web page that takes in team names, player names, and a packet, and then spits out a game you can import. I don't know if I'll have time for that in the next few months, but I'll think about it.

**Comment by alopezlago** [comment]
If I did it, I could try to follow the [QBJ Registration](https://schema.quizbowl.technology/registration) format, like

`{
teamName: string,
players: [
    {
        name: string
    }]
}`
