### ISSUE TITLE
Font change not applying despite selected font appearing to exist

### ISSUE THREAD

**Issue by ani-per** [alopezlago/MODAQ#224]
I opened the MODAQ demo page for the first time in a while to see the new features, and the previous game that I had read using it was loaded from back then.

I was able to successfully change the font from Arial to Helvetica, Courier New, Georgia, Helvetica, Tahoma, Times New Roman, and Verdana but when I tried changing it to Consolas, Garamond, or Segoe UI, the font fell back to Times New Roman despite the preview text for those three fonts successfully rendering them.

This is visible in this video (this link might expire, but I can upload it somewhere else if necessary, just tag me): https://streamable.com/j316j9

My platform is MacOS arm64 using Brave Browser v. 1.51.118 with Chromium v. 113.0.5672.126.

**Comment by alopezlago** [comment]
Certain fonts are OS specific (Consolas is a Windows-only font). Unfortunately JS doesn't have a great way of determining if a font exists on the system; [`document.fonts.check` is inconsistent](https://github.com/w3c/csswg-drafts/issues/5744). There are some hacks you can do with measuring the width of an element, which is something I could do to make the font family dialog more usable.
