### ISSUE TITLE
Reordering the team on the right copies them to the team on the left

### ISSUE THREAD

**Issue by theraggedflygon** [alopezlago/MODAQ#246]
When trying to reorder players for the team that is on the right of the screen, MODAQ will instead copy the team from the right to the left (and complete the reorder) such that the team you wanted to be on the right will now be on the left as well in the desired order.

**Comment by alopezlago** [comment]
Does this happen for any re-ordering or just moving it to a specific spot (like the front)?

**Comment by alopezlago** [comment]
I see, it's only in the new game dialog. This is a pretty bad bug; I'll give this my highest priority. For now you can work around it by re-ordering the player in the Reorder Player dialog under Actions | Reorder Players...

**Comment by alopezlago** [comment]
Fixed by #249. Should work now.
