### ISSUE TITLE
Cannot add a substitute to a team of less than four players to increase their player count by one

### ISSUE THREAD

**Issue by theraggedflygon** [alopezlago/MODAQ#247]
If a team has less than four players active in a game, but more players on their bench, you should be able to add a player who is on the team but not currently active provided the total number of players will then be less than or equal to four. 

Currently you are able to substitute out any of the active players for a bench player, and you can add a player to a roster but you cannot add a rostered player to the active squad.

An example of when this would be necessary is a team of four has their fourth player show up 30 minutes late to the first game since they overslept and show up while the rest of their team is on tossup 15.

**Comment by alopezlago** [comment]
Related to #191.

**Comment by alopezlago** [comment]
I think the solution is to change "Add Player..." to be a sub-menu, and the options are either "New player..." or a player on the bench.
