### ISSUE TITLE
Utility for generating QBJ rosters from spreadsheet

### ISSUE THREAD

**Issue by InfiniteStryker0** [alopezlago/MODAQ#253]

**Comment by alopezlago** [comment]
I need to document it better, but this helps generate files. If the team name is on the same line as the players, then you can copy and paste the values from the spreadsheet: https://www.quizbowlreader.com/createTournamentFile.html

**Comment by ani-per** [comment]
> I need to document it better, but this helps generate files. If the team name is on the same line as the players, then you can copy and paste the values from the spreadsheet: https://www.quizbowlreader.com/createTournamentFile.html

Would it be possible to add that link to the main page and/or the README?

**Comment by alopezlago** [comment]
The next version will have a link to that page in the From QBJ Registration tab. I won't make a separate utility for generating this from a spreadsheet, so I close this item when that goes in.
