### ISSUE TITLE
Use more readable default line-height (at least 1.4)

### ISSUE THREAD

**Issue by hftf** [alopezlago/MODAQ#270]
Particularly important for tossups, although the same style makes sense to apply to bonuses.

**Comment by alopezlago** [comment]
I'll have to do more research. I don't override this and [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) says that the default value is 1.2. There's some extra padding before answers to make the question/answer separation clearer, but I don't think that's what you're referencing.

**Comment by alopezlago** [comment]
Would have to go in the Font dialog, though I'm wondering if a free text field or drop down with some sensible values makes the most sense.

**Comment by alopezlago** [comment]
This does look better. I think I'm just going to set it as the default and make it non-configurable for now.
