### ISSUE TITLE
Add button to swap "First team" and "Second team" in roster entry

### ISSUE THREAD

**Issue by hftf** [alopezlago/MODAQ#274]

**Comment by alopezlago** [comment]
So is this just in the New Game dialog? Is this for manual entry too or just roster entry?

**Comment by hftf** [comment]
I'm not exactly sure what distinction you're making, sorry. The main use case on my mind was you enter the upcoming teams  before the match to save time, and when the teams enter they sit in the opposite positions from how you entered it, so you have to completely redo the roster entry instead of pressing a single button.

**Comment by alopezlago** [comment]
So would this only be in the New Game dialog, or something you have to access through a menu?
