### ISSUE TITLE
Support superpowers

### ISSUE THREAD

**Issue by geoffrey-wu** [alopezlago/MODAQ#278]
Would have to make some assumption about what superpowers look like - I think the two most common are (+) and (**). This could go under the "freeform" format? An example of a set that uses superpowers is [2023 ARCHIVE](https://collegiate.quizbowlpackets.com/2982/).

**Comment by alopezlago** [comment]
MODAQ does support superpowers (and an arbitrary number of superpower levels), but you have to customize the game format in Options | Format...

You have to do this for each game right now, but the better way to deal with it is
1. Use a wizard where it's easy to keep the current format or upload one (#216)
2. Use something like TMS that uses MODAQ as a component and can pass in the same game format each round

![image](https://github.com/alopezlago/MODAQ/assets/7349141/849645fc-e18a-4141-b04e-d77abfb3f136)

**Comment by alopezlago** [comment]
Won't Fix this as it's already supported.
