### ISSUE TITLE
Add directives with square brackets to defaults

### ISSUE THREAD

**Issue by hftf** [alopezlago/MODAQ#290]
Can the conventional variants of the directives `[pause]` `[read slowly]` `[emphasize]` with square brackets be included in the list as defaults as well? Referring to this list: 

https://github.com/alopezlago/MODAQ/commit/aaa2f400786bb478b8c2a66e67514ecfa42a8220#diff-aa7f5e96a075b0a0d3665962f9f0d3c2ac5815ca105636037c0879789617b461R11

Thanks in advance, and if it's no burden please let me know whether it's possible to push an update before this Saturday.

**Comment by alopezlago** [comment]
I can take a look at this soon, but I won’t be able to do it before
Saturday.

-Alejandro
