### ISSUE TITLE
Substituting players does not maintain player position in drop-down menu

### ISSUE THREAD

**Issue by Lucashph0241** [alopezlago/MODAQ#297]
Regarding Tomas' post in #nsc-improvements during NSC, making a player substitution does not replace the old player's position with the new player.  Instead, the new player is appended on the end of the list.  For example if player E is subbed in for player B in lineup ABCD, the new lineup is ACDE rather than AECD (example taken from Tomas' post).

Another issue I noticed that is intertwined with this one is that the Rearrange Players action does not work after a substitution.  The action works just fine if a substitution has not taken place, but if one has, pressing OK on the Rearrange Players GUI results in no change (note - I also tested the action both ways on the demo site immediately before making this post to verify this).

**Comment by alopezlago** [comment]
Putting the subbed in player where the old player was is an interesting suggestion. Internally it might be tricky but I could try getting away with it by only having it affect `GameState.getActivePlayers`, which is the source of the bug you mention.
