### ISSUE TITLE
Allow drag-and-drop file uploads for better accessibility

### ISSUE THREAD

**Issue by hftf** [alopezlago/MODAQ#306]
For whatever reason my browser (Chrome on Mac) sometimes stops spawning file upload dialogs when clicking the "Load..." button after a few rounds of using MODAQ. If I could just drop packet/json files onto the button from a file explorer (which is already possible on most native file upload buttons) I wouldn't have to restart my entire browser to make it work again.

**Comment by alopezlago** [comment]
Is there anything in the Console when load stops working? Having drag+drop would be useful but it'd good to know why it stops loading new packets too.

**Comment by hftf** [comment]
Not that I'm aware of; the browser downloads/file dialog just seems to get into a stuck state – I can see the download/upload is queued but nothing you do moves it a long.

**Comment by hftf** [comment]
Thank you so much!
