### ISSUE TITLE
Scoresheet output

### ISSUE THREAD

**Issue by InfiniteStryker0** [alopezlago/MODAQ#310]
It would be useful to have the ability to output a PDF scoresheet (or some other human-readable format). Sometimes the QBJ doesn't load properly into YFT, and a backup that can be typed in manually would help with that. Also for protests and such.

**Comment by alopezlago** [comment]
PDFs are kind of a bear to generate. If you go to View | Scoresheet..., you can see a table formatted like a scoresheet, and you can copy and paste it into a spreadsheet like Excel.

**Comment by InfiniteStryker0** [comment]
That seems to work very well. Is CSV a possibility or are those also hard to generate?
