### ISSUE TITLE
Check if data exists in a scoresheet before exporting to it

### ISSUE THREAD

**Issue by hftf** [alopezlago/MODAQ#39]
The wiki says:

> Be sure that the round number is correct to make sure you don't overwrite an existing game.

We should automatically detect whether data already exists in the scoresheet before overwriting it. Ask something defensively like "Are you sure you want to overwrite the data in the Round 2 sheet?", or offer an Undo action (but it may not be worthwhile or desirable to have Undo, since it depends on the moderator noticing a problem in the first place).

Besides prompting users when the scoresheet is already filled in, it would be even better to show exactly which rounds already have data (and it may be possible to do so in 1 API call), so that the moderator can compare their expectations to that list, and the round number could be entered by clicking a button instead of typing a numeric input, which is more prone to mistakes.

> <kbd>Round 1</kbd>: ✔︎ detected data already in scoresheet
> <kbd>Round 2</kbd>: ✔︎ detected data already in scoresheet
> <kbd>Round 3</kbd>
> <kbd>Round 4</kbd>

**Comment by alopezlago** [comment]
I like the prompt and undo ideas.

Showing which rounds have data is a little more complex. I guess we could fire a Google request on a URL change, but the API calls can be slow sometimes, so it may take too long to be that useful.

**Comment by alopezlago** [comment]
I have a fix for this in a private branch. Just need to add some unit tests and I'll send a PR out for it.
