### ISSUE TITLE
Support a file-based scoresheet (xlsx file)

### ISSUE THREAD

**Issue by alopezlago** [alopezlago/MODAQ#40]
We should support a file-based scoresheet that can also record buzz points. This will be useful for the desktop-only case (#26) where we want it to work even if there's no internet connectivity.

As far as I know, there are no existing file-only spreadsheets that track advanced stats.

**Comment by alopezlago** [comment]
A big part of this is developing an xlsx scoresheet template for tracking advanced stats. It could just match what Lifsheets looks like.

It would be great to do this purely through JS, but calling an API endpoint to create it would also be okay, as long as it could be included in a desktop application (similar to YAPP for parsing).

**Comment by hftf** [comment]
> we want it to work even if there's no internet connectivity.

I'm sure you already know: modern browsers have plenty of (widely-supported) features for making "progressive web apps" that still work offline, use reliable persistent storage, have graceful fallback, automatically synchronize when reconnected, etc., which makes full-fledged desktop applications less important.

**Comment by alopezlago** [comment]
With QBJ exports supported, and Yellowfruit supporting QBJ files that MODAQ exports, I think this is no longer necessary.
